name: my_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  supabase_flutter: ^2.9.0 # Tambahkan ini
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  intl: ^0.20.2
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  table_calendar: ^3.2.0
  flutter_map_cancellable_tile_provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
